name: Continuos integration UI

on:
  workflow_call:
    inputs:
      release:
        required: false
        type: boolean
    secrets:
      RELEASE_TOKEN:
        required: false
      DISCORD_WEBHOOK:
        required: true

jobs:
  install_test_build_release:
    name: Continuos integration UI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://npm.pkg.github.com"
          scope: "@lualtek"

      - run: npm i -g npm@8

      - name: Cache Dependencies
        uses: actions/cache@v3
        env:
          cache-name: cache-node-npm
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      # Used to avoid rate limit on Changeset check on pull request using the search api
      - name: Generate token custom GithHub Token from App
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          # From ORG secrets
          app_id: ${{ secrets.LUALTEK_RELEASE_APP_ID }}
          # From ORG secrets
          private_key: ${{ secrets.LUALTEK_RELEASE_APP_PRIVATE_KEY }}

      - name: Create Release Pull Request or Publish to GitHub Packages
        id: changesets
        uses: changesets/action@v1
        if: inputs.release == true
        with:
          version: ./update-lock.sh
          publish: npm run release
          commit: "ci: release"
          title: "ci: release"
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          NPM_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.RELEASE_TOKEN }}

      - name: Send a Discord notification
        if: steps.changesets.outputs.published == 'true'
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "Release UI Components"
          description: "UI components released on NPM"
